# Generated by Django 4.2.14 on 2024-08-01 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, null=True)),
                ('customer_since', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, null=True)),
                ('order_date', models.DateField(null=True)),
                ('quantity', models.FloatField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('gst_amount', models.FloatField(default=0)),
                ('bill_amount', models.FloatField(default=0)),
                ('customer_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OrderManagement.customer')),
                ('product_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.product')),
            ],
        ),
    ]
