# Generated by Django 4.2.14 on 2024-08-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, null=True)),
                ('product_code', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(default=0)),
                ('gst', models.IntegerField(default=0)),
                ('food_product', models.BooleanField(default=False)),
                ('picture', models.ImageField(null=True, upload_to='imgaes/')),
            ],
        ),
    ]
